/**
 * ThirdPersonBody.ts — the "Invisible Master Skeleton" of the unified
 * character architecture (FPS/TPS Spec §1).
 *
 * ONE logical entity, TWO visual representations. This module owns the 3PS
 * half: a rigid low-poly body rig (code-generated by tools/generateBodyModel.js)
 * positioned at the player capsule's simulated world transform — NOT parented
 * to the camera, which is what distinguishes it from the viewmodel rig.
 *
 * Responsibilities, all strictly visual (this file never touches the sim):
 *   - place/orient the body from PlayerMovement's authoritative state;
 *   - drive procedural locomotion (stride-synced hips/knees/arms) — the rig
 *     is rigid, so there are no baked leg clips, exactly as Document A
 *     resolved for the arms;
 *   - apply the Aim Offset (§4): normalized pitch/yaw distributed across the
 *     spine chain so the external silhouette matches where the 1PS camera
 *     is looking, in absolute real time;
 *   - expose Socket_Eyes / Socket_CameraPivot for PerspectiveController, and
 *     the arm chains for weapon-grip IK;
 *   - perspective masking: the head/helmet/neck meshes move to the viewmodel
 *     layer in 1PS (so the camera inside the skull sees nothing) while STILL
 *     casting shadows, because the shadow pass tests against the light's
 *     camera, never the player camera's mask.
 */
import * as THREE from 'three';
import {
  AIM_OFFSET, FOOT_IK, PERSPECTIVE, PLAYER, TPS_LOCOMOTION,
} from '../utils/Constants';
import { LAYER, setLayerRecursive } from '../core/RenderLayers';
import { TPS_CARRY } from '../utils/Constants';
import { clamp, lerp } from '../utils/MathUtils';
import type { AssetLoader } from '../core/AssetLoader';
import type { JointChain } from './JointIK';

export interface BodyPoseInput {
  /** Feet position of the capsule (authoritative sim). */
  position: THREE.Vector3;
  /** Look yaw (radians) — the controller rotation, not the body facing. */
  aimYaw: number;
  /** Look pitch (radians), −up/+down per the project's YXZ convention. */
  aimPitch: number;
  /** Horizontal speed (m/s). */
  speed: number;
  /** Local-space velocity: +z forward, +x right (drives strafe blending). */
  localVelocity: { x: number; z: number };
  isGrounded: boolean;
  /** Live capsule height — crouch/slide compress it. */
  capsuleHeight: number;
  movementState: string;
  /** Suppresses locomotion while a vault drives the body explicitly. */
  traversalActive: boolean;
}

/** Downward ground probe, supplied by whoever owns the collision world. */
export type GroundProbe = (origin: THREE.Vector3, maxDistance: number)
  => { point: THREE.Vector3; normal: THREE.Vector3 } | null;

interface LegNodes {
  hip: THREE.Object3D;
  knee: THREE.Object3D;
  ankle: THREE.Object3D;
  sole: THREE.Object3D;
  /** Foot-IK state: current eased vertical correction and sole normal. */
  ikOffset: number;
  ikPitch: number;
}

const _v = new THREE.Vector3();
const _v2 = new THREE.Vector3();
const _euler = new THREE.Euler();
const _quat = new THREE.Quaternion();
const _eyeWorld = new THREE.Vector3();
const _rootWorld = new THREE.Vector3();
const _eyeLocal = new THREE.Vector3();
const _bbox = new THREE.Box3();

export class ThirdPersonBody {
  private root: THREE.Group | null = null;
  private pelvis: THREE.Object3D | null = null;
  private spine: THREE.Object3D | null = null;
  private chest: THREE.Object3D | null = null;
  private neck: THREE.Object3D | null = null;
  private head: THREE.Object3D | null = null;
  private eyes: THREE.Object3D | null = null;
  private cameraPivot: THREE.Object3D | null = null;
  private readonly legs: Record<'R' | 'L', LegNodes | null> = { R: null, L: null };
  private readonly arms: Record<'R' | 'L', JointChain | null> = { R: null, L: null };
  private readonly headMeshes: THREE.Object3D[] = [];
  /** Rest local transforms — every frame rebuilds pose = rest + procedural. */
  private readonly restQuat = new Map<THREE.Object3D, THREE.Quaternion>();
  private readonly restPos = new Map<THREE.Object3D, THREE.Vector3>();

  /** Body facing (radians). Lags aim yaw; re-plants past the twist limit. */
  private bodyYaw = 0;
  /** Eased aim-offset blend-space coordinates. */
  private blendPitch = 0;
  private blendYaw = 0;
  private stridePhase = 0;
  /** Eased pose weights for crouch/slide/air. */
  private crouchWeight = 0;
  private slideWeight = 0;
  private airWeight = 0;
  private pelvisIkDrop = 0;

  /**
   * Nodes owned by an EXTERNAL driver (HandsRig's springs + the weapon IK).
   * In unified-character mode the arms are posed by the same code that posed
   * the old viewmodel arms, so this rig must not restore or animate them —
   * doing so silently overwrote the IK every frame and left the arms hanging.
   */
  private readonly externallyDriven = new Set<THREE.Object3D>();
  private armsExternallyDriven = false;

  private weaponProp: THREE.Object3D | null = null;
  /** Half the chest's front-to-back depth, measured from the loaded model. */
  private torsoHalfDepth = 0.12;
  private groundProbe: GroundProbe | null = null;
  private footIkEnabled = true;
  private ready = false;


  constructor(private readonly assetLoader: AssetLoader) {}

  async load(scene: THREE.Scene): Promise<void> {
    const model = await this.assetLoader.loadModel(PERSPECTIVE.BODY_PATH);
    this.root = model;
    const byName = (n: string): THREE.Object3D | null => model.getObjectByName(n) ?? null;

    this.pelvis = byName('Bone_Pelvis');
    this.spine = byName('Bone_Spine');
    this.chest = byName('Bone_Chest');
    this.neck = byName('Bone_Neck');
    this.head = byName('Bone_Head');
    this.eyes = byName('Socket_Eyes');
    this.cameraPivot = byName('Socket_CameraPivot');

    for (const side of ['R', 'L'] as const) {
      const hip = byName(`HipPivot_${side}`);
      const knee = byName(`KneePivot_${side}`);
      const ankle = byName(`AnklePivot_${side}`);
      const sole = byName(`Socket_Sole_${side}`);
      if (hip && knee && ankle && sole) {
        this.legs[side] = { hip, knee, ankle, sole, ikOffset: 0, ikPitch: 0 };
      }
      const shoulder = byName(`Shoulder_${side}`);
      const upperArm = byName(`UpperArmPivot_${side}`);
      const elbow = byName(`ElbowPivot_${side}`);
      const wrist = byName(`WristPivot_${side}`);
      if (shoulder && upperArm && elbow && wrist) {
        this.arms[side] = { shoulderPivot: shoulder, upperArmPivot: upperArm, elbowPivot: elbow, wristPivot: wrist };
      }
    }

    if (!this.pelvis || !this.spine || !this.chest || !this.neck || !this.head
      || !this.eyes || !this.cameraPivot || !this.legs.R || !this.legs.L) {
      throw new Error('[ThirdPersonBody] body rig is missing mandatory nodes — regenerate (node tools/generateBodyModel.js)');
    }

    for (const name of PERSPECTIVE.HEAD_MESHES) {
      const mesh = byName(name);
      if (mesh) this.headMeshes.push(mesh);
    }

    // Measure the torso's front-to-back depth straight off the asset, so the
    // eye-anchoring setback adapts to any character proportions.
    const chestMesh = byName('Mesh_Chest') ?? byName('Mesh_Spine');
    if (chestMesh) {
      _bbox.setFromObject(chestMesh);
      this.torsoHalfDepth = Math.max(0.05, (_bbox.max.z - _bbox.min.z) * 0.5);
    }

    // Capture rest pose: every frame writes rest × procedural, never
    // accumulating (the same invariant HandsRig relies on).
    model.traverse((o) => {
      this.restQuat.set(o, o.quaternion.clone());
      this.restPos.set(o, o.position.clone());
      const mesh = o as THREE.Mesh;
      if (mesh.isMesh) {
        mesh.castShadow = true;
        mesh.receiveShadow = true;
      }
    });

    this.assignLayers();
    scene.add(model);
    this.ready = true;
  }

  /** Ground query used by foot IK (ColliderFactory/Rapier in practice). */
  setGroundProbe(probe: GroundProbe | null): void {
    this.groundProbe = probe;
  }

  setFootIkEnabled(enabled: boolean): void {
    this.footIkEnabled = enabled;
  }

  get isReady(): boolean {
    return this.ready;
  }

  get object(): THREE.Group | null {
    return this.root;
  }

  /** Shared-naming arm chains — the SAME contract the viewmodel rig exposes. */
  getArmChain(side: 'R' | 'L'): JointChain | null {
    return this.arms[side];
  }

  /** World transform of the 3PS skeleton's eye socket (1PS camera anchor). */
  getEyeWorldPosition(out: THREE.Vector3): THREE.Vector3 {
    if (!this.eyes) return out.set(0, 0, 0);
    return this.eyes.getWorldPosition(out);
  }

  /** World transform of the spring-arm origin (3PS camera boom anchor). */
  getBoomAnchorWorldPosition(out: THREE.Vector3): THREE.Vector3 {
    if (!this.cameraPivot) return out.set(0, 0, 0);
    return this.cameraPivot.getWorldPosition(out);
  }

  /** TEST/debug seam. */
  get currentBodyYaw(): number {
    return this.bodyYaw;
  }

  get aimBlend(): { pitch: number; yaw: number } {
    return { pitch: this.blendPitch, yaw: this.blendYaw };
  }

  get headMeshLayerMask(): number {
    return this.headMeshes[0]?.layers.mask ?? 0;
  }

  /**
   * §1 Perspective toggling: a pure LAYER operation.
   *
   *  - 3PS: every node sits on BODY_LAYER_INDEX → the world pass (which the
   *    camera runs with a mask covering layers 0 and 2) draws the whole body.
   *  - 1PS: the head/helmet/neck move to the VIEWMODEL layer. The world pass
   *    skips them (not in its mask) and the viewmodel pass runs after a depth
   *    clear at point-blank range, so they contribute nothing visible either.
   *    They stay in the scene graph with castShadow = true, so the full-body
   *    shadow is unbroken — the spec's "Shadows Only" requirement without a
   *    second material or a second mesh.
   */
  setPerspective(_perspective: 'FIRST' | 'THIRD'): void {
    // No re-layering needed: the split is static (body = CHARACTER, head =
    // HEAD) and the CAMERA's mask decides what each perspective sees. That
    // keeps the toggle free of per-object work and impossible to half-apply.
  }

  /**
   * Static layer assignment (see core/RenderLayers.ts):
   *   - the whole body goes on CHARACTER, so it is visible in BOTH
   *     perspectives — this is what lets you look down in first person and
   *     see your own torso and legs;
   *   - the head/helmet/neck go on HEAD, which the first-person camera mask
   *     omits (you cannot see the inside of your own skull) while the shadow
   *     pass still renders them, keeping the cast silhouette whole;
   *   - the ARMS are NOT re-layered here: WeaponViewmodel moves them (and the
   *     held weapon) to the VIEWMODEL layer so they draw in the depth-cleared
   *     pass and can never clip into walls.
   */
  private assignLayers(): void {
    if (!this.root) return;
    setLayerRecursive(this.root, LAYER.CHARACTER);
    for (const mesh of this.headMeshes) setLayerRecursive(mesh, LAYER.HEAD);
    // The rig's own arms (and anything parented to them, i.e. the 3P weapon)
    // are third-person-only; the viewmodel replaces them in first person.
    for (const side of ['R', 'L'] as const) {
      const chain = this.arms[side];
      if (chain) setLayerRecursive(chain.shoulderPivot, LAYER.BODY_ARMS);
    }
  }

  /**
   * Hand the arms over to HandsRig/WeaponIK. Their subtrees are then excluded
   * from this rig's rest-restore and procedural arm swing, so the two systems
   * never fight over the same joints.
   */
  setArmsExternallyDriven(driven: boolean): void {
    this.armsExternallyDriven = driven;
    this.externallyDriven.clear();
    if (!driven) return;
    for (const side of ['R', 'L'] as const) {
      const chain = this.arms[side];
      if (chain) chain.shoulderPivot.traverse((o) => this.externallyDriven.add(o));
    }
  }

  /**
   * Third-person weapon prop: a copy of the equipped weapon parented under the
   * body's right wrist, with the off-hand posed onto it.
   *
   * This is the standard hybrid approach — the first-person viewmodel and the
   * third-person prop are separate meshes, but they are driven from ONE
   * gameplay state (same weapon id, same equip event, same logical animation
   * timings via PerspectiveSync), so an observer and the player always see the
   * same weapon doing the same thing at the same moment.
   */
  setWeaponProp(prop: THREE.Object3D | null, gripLocal: { x: number; y: number; z: number }): void {
    if (this.weaponProp) {
      this.weaponProp.parent?.remove(this.weaponProp);
      this.weaponProp = null;
    }
    const wrist = this.arms.R?.wristPivot;
    if (!prop || !wrist) return;
    setLayerRecursive(prop, LAYER.BODY_ARMS);
    prop.position.set(gripLocal.x, gripLocal.y, gripLocal.z);
    prop.quaternion.identity();
    wrist.add(prop);
    this.weaponProp = prop;
  }

  /** Carry pose: both arms brought up onto the weapon (two-handed hold). */
  private applyWeaponCarryPose(): void {
    if (!this.weaponProp) return;
    const c = TPS_CARRY;
    this.rotateLocal(this.arms.R?.upperArmPivot, c.RIGHT_UPPER.x, c.RIGHT_UPPER.y, c.RIGHT_UPPER.z);
    this.rotateLocal(this.arms.R?.elbowPivot, c.RIGHT_ELBOW.x, c.RIGHT_ELBOW.y, c.RIGHT_ELBOW.z);
    this.rotateLocal(this.arms.L?.upperArmPivot, c.LEFT_UPPER.x, c.LEFT_UPPER.y, c.LEFT_UPPER.z);
    this.rotateLocal(this.arms.L?.elbowPivot, c.LEFT_ELBOW.x, c.LEFT_ELBOW.y, c.LEFT_ELBOW.z);
  }

  /** The arm chains, for the shared HandsRig to drive (unified character). */
  get armChains(): { R: JointChain | null; L: JointChain | null } {
    return { R: this.arms.R, L: this.arms.L };
  }

  /**
   * Per-frame visual update. Order matters and mirrors the viewmodel rig:
   *   1. restore the rest pose (absolute writes, never accumulate),
   *   2. root placement from the sim,
   *   3. procedural locomotion (stride/crouch/slide/air),
   *   4. aim offset across the spine chain,
   *   5. foot IK against real ground.
   */
  update(dt: number, input: BodyPoseInput): void {
    if (!this.ready || !this.root) return;

    for (const [node, rest] of this.restQuat) {
      if (this.externallyDriven.has(node)) continue;
      node.quaternion.copy(rest);
    }
    for (const [node, rest] of this.restPos) {
      if (this.externallyDriven.has(node)) continue;
      node.position.copy(rest);
    }

    this.updateBodyYaw(dt, input);
    this.root.position.copy(input.position);
    this.root.rotation.set(0, this.bodyYaw, 0);
    // Eye-anchoring is applied after the full pose is built (see the call to
    // anchorEyesToCamera at the end of this method): the head is posed by the
    // aim offset, so the eye socket's offset is only known once that has run.

    // Crouch/slide compress the capsule; the rig scales its stance to match
    // so the body's head never floats above the real collision volume.
    const crouchAmount = clamp(
      (PLAYER.STAND_HEIGHT - input.capsuleHeight) / (PLAYER.STAND_HEIGHT - PLAYER.CROUCH_HEIGHT),
      0, 1,
    );
    const sliding = input.movementState === 'SLIDE';
    const rate = Math.min(1, TPS_LOCOMOTION.POSE_RATE * dt);
    this.crouchWeight = lerp(this.crouchWeight, sliding ? 0 : crouchAmount, rate);
    this.slideWeight = lerp(this.slideWeight, sliding ? 1 : 0, rate);
    this.airWeight = lerp(this.airWeight, input.isGrounded ? 0 : 1, rate);

    if (!input.traversalActive) {
      this.applyLocomotion(dt, input);
    }
    this.applyStancePose();
    this.applyWeaponCarryPose();
    this.applyAimOffset(dt, input);
    this.root.updateMatrixWorld(true);
    if (this.footIkEnabled && input.isGrounded && !input.traversalActive) {
      this.applyFootIK(dt, input);
    } else {
      this.relaxFootIK(dt);
    }
    this.anchorEyesToCamera(input);
  }

  /**
   * Slide the rig horizontally so its EYE SOCKET sits exactly under the
   * camera, then push the body back by its own torso depth.
   *
   * Why this is needed: the root was pinned to the capsule centre, but the
   * rig's eyes sit forward of the hip axis (the face is on the front of the
   * head). Anchoring the feet instead of the eyes therefore placed the whole
   * skeleton — including the thighs — forward of where the player's viewpoint
   * actually is, which is why the legs appeared to be *in front of* the camera
   * instead of below and behind it.
   *
   * Everything here is MEASURED from the loaded model at runtime
   * (`eyeForwardOffset`, `torsoHalfDepth`), so a taller or differently
   * proportioned character rig works with no constant to retune.
   */
  private anchorEyesToCamera(input: BodyPoseInput): void {
    if (!this.root || !this.eyes) return;
    // Measured eye offset in the body's own frame, along its facing axis.
    _eyeWorld.setFromMatrixPosition(this.eyes.matrixWorld);
    _rootWorld.setFromMatrixPosition(this.root.matrixWorld);
    _eyeLocal.copy(_eyeWorld).sub(_rootWorld);
    // Body faces -Z in its own space; project the eye offset onto that axis.
    const forwardX = -Math.sin(this.bodyYaw);
    const forwardZ = -Math.cos(this.bodyYaw);
    const eyeForward = _eyeLocal.x * forwardX + _eyeLocal.z * forwardZ;
    // Pull the rig back so the eyes land on the camera, plus enough clearance
    // that the chest/thighs stay behind the lens rather than straddling it.
    const setback = eyeForward + this.torsoHalfDepth * PERSPECTIVE.BODY_SETBACK_FACTOR;
    this.root.position.x -= forwardX * setback;
    this.root.position.z -= forwardZ * setback;
    this.root.updateMatrixWorld(true);
    void input;
  }

  /**
   * §4 turn-in-place: the body doesn't rigidly track the aim. It holds facing
   * while the torso twists (the Aim Offset absorbs it) until the twist exceeds
   * REPLANT_YAW_RAD, then the feet re-plant to catch up. While moving, the
   * body faces the movement direction blended toward the aim.
   */
  private updateBodyYaw(dt: number, input: BodyPoseInput): void {
    const moving = input.speed > 0.35;
    if (moving) {
      // Facing follows the aim while moving (strafing is expressed by the
      // procedural stride's lateral lean, not by rotating the whole body).
      this.bodyYaw = approachAngle(this.bodyYaw, input.aimYaw, AIM_OFFSET.REPLANT_RATE * 1.6 * dt);
      return;
    }
    const twist = wrapAngle(input.aimYaw - this.bodyYaw);
    if (Math.abs(twist) > AIM_OFFSET.REPLANT_YAW_RAD) {
      const excess = Math.abs(twist) - AIM_OFFSET.REPLANT_YAW_RAD;
      this.bodyYaw = wrapAngle(this.bodyYaw + Math.sign(twist) * Math.min(excess + 0.02, AIM_OFFSET.REPLANT_RATE * dt));
    }
  }

  /** Procedural stride: rigid rig, so hips/knees/arms are driven by math. */
  private applyLocomotion(dt: number, input: BodyPoseInput): void {
    const speed = input.speed;
    const amp = Math.min(1, speed / TPS_LOCOMOTION.SPEED_REF);

    // --- cadence derived from GROUND DISTANCE, not a tuned constant --------
    // The old formula advanced the phase at STRIDE_HZ_PER_SPEED * max(1, speed),
    // so the legs cycled at a fixed rate that had no relationship to how far
    // the body actually travelled — and the max(1, ...) floor made them
    // windmill at full cadence even while barely creeping forward. That is
    // the "legs moving faster than us" foot-sliding artefact.
    //
    // Correct relationship: a stride swings the foot forward by
    // legLength * sin(hipSwing), so one full two-step cycle covers
    // 4 * legLength * sin(hipSwing) metres of ground. Cycles per second is
    // therefore speed / cycleDistance, which makes the planted foot stay
    // put under the body at every speed.
    if (speed > 0.35 && input.isGrounded) {
      const swingRad = TPS_LOCOMOTION.HIP_SWING_RAD * Math.max(amp, 0.25);
      const cycleDistance = Math.max(
        0.4,
        4 * TPS_LOCOMOTION.LEG_LENGTH * Math.sin(swingRad),
      );
      const cyclesPerSecond = speed / cycleDistance;
      this.stridePhase += dt * Math.PI * 2 * cyclesPerSecond;
    }
    if (amp <= 0.001 || !input.isGrounded) return;

    // Direction sign: walking backwards reverses the stride so the legs never
    // appear to moonwalk (spec §3 "velocity, not input, drives the loop").
    const dir = input.localVelocity.z >= 0 ? 1 : -1;
    const phase = this.stridePhase * dir;
    const swing = Math.sin(phase) * TPS_LOCOMOTION.HIP_SWING_RAD * amp;
    // Knees only ever FLEX (negative-x bend on this rig), never hyperextend.
    const kneeR = -Math.max(0, -Math.cos(phase)) * TPS_LOCOMOTION.KNEE_BEND_RAD * amp;
    const kneeL = -Math.max(0, Math.cos(phase)) * TPS_LOCOMOTION.KNEE_BEND_RAD * amp;

    this.rotateLocal(this.legs.R?.hip, swing, 0, 0);
    this.rotateLocal(this.legs.L?.hip, -swing, 0, 0);
    this.rotateLocal(this.legs.R?.knee, kneeR, 0, 0);
    this.rotateLocal(this.legs.L?.knee, kneeL, 0, 0);
    // Ankles counter-rotate so the soles stay roughly parallel to the ground.
    this.rotateLocal(this.legs.R?.ankle, -swing * 0.4 - kneeR * 0.5, 0, 0);
    this.rotateLocal(this.legs.L?.ankle, swing * 0.4 - kneeL * 0.5, 0, 0);

    // Counter-swinging arms (opposite phase to their same-side leg). The
    // weapon-grip IK, when active, overrides these — arms holding a rifle
    // ride with the weapon instead (§4 sync matrix).
    // Skipped entirely while the arms are IK-driven: a rifle carried in two
    // hands does not counter-swing, and HandsRig already owns the sprint /
    // tac-sprint / free-swing poses for those joints.
    if (!this.armsExternallyDriven) {
      const armSwing = -Math.sin(phase) * TPS_LOCOMOTION.ARM_SWING_RAD * amp;
      this.rotateLocal(this.arms.R?.shoulderPivot, -armSwing, 0, 0);
      this.rotateLocal(this.arms.L?.shoulderPivot, armSwing, 0, 0);
    }

    // Subtle vertical bob at twice the stride frequency (both feet per cycle).
    if (this.pelvis) this.pelvis.position.y += Math.sin(phase * 2) * 0.018 * amp;
  }

  /** Crouch / slide / air stance blended over the stride. */
  private applyStancePose(): void {
    const c = this.crouchWeight;
    const s = this.slideWeight;
    const a = this.airWeight;
    if (c > 0.001) {
      const k = TPS_LOCOMOTION.CROUCH;
      if (this.pelvis) this.pelvis.position.y -= k.PELVIS_DROP * c;
      for (const side of ['R', 'L'] as const) {
        this.rotateLocal(this.legs[side]?.hip, k.HIP_BEND * c, 0, 0);
        this.rotateLocal(this.legs[side]?.knee, -k.KNEE_BEND * c, 0, 0);
        this.rotateLocal(this.legs[side]?.ankle, (k.KNEE_BEND - k.HIP_BEND) * c, 0, 0);
      }
    }
    if (s > 0.001) {
      const k = TPS_LOCOMOTION.SLIDE;
      if (this.pelvis) this.pelvis.position.y -= k.PELVIS_DROP * s;
      this.rotateLocal(this.spine, -k.LEAN_BACK * s, 0, 0);
      // Lead leg extends, trailing leg tucks — the classic slide silhouette.
      this.rotateLocal(this.legs.R?.hip, k.HIP_BEND * 0.35 * s, 0, 0);
      this.rotateLocal(this.legs.L?.hip, k.HIP_BEND * s, 0, 0);
      this.rotateLocal(this.legs.L?.knee, -k.KNEE_BEND * s, 0, 0);
    }
    if (a > 0.001) {
      const k = TPS_LOCOMOTION.AIR;
      for (const side of ['R', 'L'] as const) {
        this.rotateLocal(this.legs[side]?.hip, k.HIP_BEND * a, 0, 0);
        this.rotateLocal(this.legs[side]?.knee, -k.KNEE_BEND * a, 0, 0);
      }
    }
  }

  /**
   * §4 The Aim Offset Pattern. A 9-frame blend space exists to interpolate
   * SKINNED poses; a rigid rig can evaluate the same 2D space analytically —
   * normalized pitch/yaw distributed down the spine chain. The result is
   * identical in intent (spine bones blend in absolute real time to match
   * where the 1PS camera looks) with no pose assets to author or ship.
   */
  private applyAimOffset(dt: number, input: BodyPoseInput): void {
    const targetPitch = clamp(input.aimPitch, -AIM_OFFSET.MAX_PITCH_RAD, AIM_OFFSET.MAX_PITCH_RAD);
    const targetYaw = clamp(wrapAngle(input.aimYaw - this.bodyYaw), -AIM_OFFSET.MAX_YAW_RAD, AIM_OFFSET.MAX_YAW_RAD);
    const k = Math.min(1, AIM_OFFSET.BLEND_RATE * dt);
    this.blendPitch = lerp(this.blendPitch, targetPitch, k);
    this.blendYaw = lerp(this.blendYaw, targetYaw, k);

    const p = AIM_OFFSET.PITCH_DISTRIBUTION;
    const y = AIM_OFFSET.YAW_DISTRIBUTION;
    this.rotateLocal(this.pelvis, this.blendPitch * p.pelvis, this.blendYaw * y.pelvis, 0);
    this.rotateLocal(this.spine, this.blendPitch * p.spine, this.blendYaw * y.spine, 0);
    this.rotateLocal(this.chest, this.blendPitch * p.chest, this.blendYaw * y.chest, 0);
    this.rotateLocal(this.neck, this.blendPitch * p.neck, this.blendYaw * y.neck, 0);
    this.rotateLocal(this.head, this.blendPitch * p.head, this.blendYaw * y.head, 0);
  }

  /**
   * Two-bone foot IK (§4 sync matrix): trace down from each rest sole, then
   * ease the ankle onto the surface and pitch the foot to its normal. The
   * pelvis drops by the deepest correction so the low foot can actually
   * reach, which is what sells uneven terrain.
   */
  private applyFootIK(dt: number, input: BodyPoseInput): void {
    if (!this.groundProbe || !this.pelvis) return;
    const k = Math.min(1, FOOT_IK.BLEND_RATE * dt);
    let deepest = 0;
    const solved: Array<{ leg: LegNodes; offset: number; pitch: number }> = [];

    for (const side of ['R', 'L'] as const) {
      const leg = this.legs[side];
      if (!leg) continue;
      leg.sole.getWorldPosition(_v);
      _v2.set(_v.x, _v.y + FOOT_IK.PROBE_UP, _v.z);
      const hit = this.groundProbe(_v2, FOOT_IK.PROBE_UP + FOOT_IK.PROBE_DOWN);
      let offset = 0;
      let pitch = 0;
      if (hit) {
        const raw = hit.point.y - _v.y;
        if (Math.abs(raw) > FOOT_IK.DEADZONE) offset = raw;
        // Pitch the foot to the slope, in the body's facing frame.
        const nLocal = _v2.copy(hit.normal).applyAxisAngle(UP, -this.bodyYaw);
        pitch = Math.atan2(nLocal.z, nLocal.y);
      }
      offset = clamp(offset, -FOOT_IK.MAX_PELVIS_DROP, FOOT_IK.MAX_PELVIS_DROP);
      solved.push({ leg, offset, pitch });
      deepest = Math.min(deepest, offset);
    }

    // Pelvis drops to the lowest foot; each foot's correction is relative.
    this.pelvisIkDrop = lerp(this.pelvisIkDrop, deepest, k);
    this.pelvis.position.y += this.pelvisIkDrop;
    for (const { leg, offset, pitch } of solved) {
      leg.ikOffset = lerp(leg.ikOffset, offset - deepest, k);
      leg.ikPitch = lerp(leg.ikPitch, pitch, k);
      // Rigid rig: shorten the chain by rotating hip+knee rather than
      // translating the ankle (translating would visibly detach the segments).
      // ikOffset is >= 0 by construction (the pelvis already absorbed the
      // deepest correction), so this leg only ever needs to COMPRESS — hip
      // flexes forward, knee flexes back, exactly like the crouch stance.
      // The knee contribution must stay negative: a positive rotation here
      // hyperextends the joint backwards, which reads as a broken leg.
      const reach = Math.max(0, leg.ikOffset);
      if (reach > FOOT_IK.DEADZONE) {
        this.rotateLocal(leg.hip, reach * 0.75, 0, 0);
        this.rotateLocal(leg.knee, -reach * 1.5, 0, 0);
      }
      this.rotateLocal(leg.ankle, leg.ikPitch, 0, 0);
    }
    void input;
  }

  private relaxFootIK(dt: number): void {
    const k = Math.min(1, FOOT_IK.BLEND_RATE * dt);
    this.pelvisIkDrop = lerp(this.pelvisIkDrop, 0, k);
    for (const side of ['R', 'L'] as const) {
      const leg = this.legs[side];
      if (!leg) continue;
      leg.ikOffset = lerp(leg.ikOffset, 0, k);
      leg.ikPitch = lerp(leg.ikPitch, 0, k);
    }
  }

  /** Right-multiply a local XYZ euler delta onto a node (never accumulates:
   *  the rest pose was restored at the top of update()). */
  private rotateLocal(node: THREE.Object3D | null | undefined, x: number, y: number, z: number): void {
    if (!node || (x === 0 && y === 0 && z === 0)) return;
    _euler.set(x, y, z, 'XYZ');
    _quat.setFromEuler(_euler);
    node.quaternion.multiply(_quat);
  }

  dispose(): void {
    this.root?.parent?.remove(this.root);
    this.root = null;
    this.ready = false;
  }
}

const UP = new THREE.Vector3(0, 1, 0);

/** Wrap to (−π, π]. */
export function wrapAngle(a: number): number {
  let x = a;
  while (x > Math.PI) x -= Math.PI * 2;
  while (x <= -Math.PI) x += Math.PI * 2;
  return x;
}

/** Move `from` toward `to` by at most `maxDelta`, along the short arc. */
export function approachAngle(from: number, to: number, maxDelta: number): number {
  const diff = wrapAngle(to - from);
  if (Math.abs(diff) <= maxDelta) return wrapAngle(to);
  return wrapAngle(from + Math.sign(diff) * maxDelta);
}

export default ThirdPersonBody;
