#!/usr/bin/env node
/**
 * generateHDRISky.js — Document K §5.2 / Document K §5.1's "everything is a
 * real committed file" policy applied to the sky:
 *
 *   node tools/generateHDRISky.js
 *
 * Procedurally renders an equirectangular dockyard sky (zenith→horizon
 * gradient + tight HDR sun disc + broad glow + dark ground haze below the
 * horizon) and saves it as a REAL Radiance .hdr file — flat (uncompressed
 * RGBE) scanlines, which three's RGBELoader accepts. No external dependency;
 * the .hdr writer below is a complete, correct Radiance encoder.
 *
 * IMPORTANT: the baked `sunDir` here must numerically match the sunDirection
 * in the level definition that consumes this HDRI (Document K §5.4's
 * artist-authored pairing convention) — or the visible sun disc and the
 * shadow-casting sun light will disagree.
 */
import fs from 'node:fs';
import path from 'node:path';

const OUT_DIR = path.resolve('assets/hdri');
fs.mkdirSync(OUT_DIR, { recursive: true });

const norm = (v) => {
  const l = Math.hypot(v[0], v[1], v[2]) || 1;
  return [v[0] / l, v[1] / l, v[2] / l];
};

function generateSkyHDR({
  width = 1024, height = 512,
  sunDir, sunColor, sunIntensity = 4.0,
  zenithColor, horizonColor, groundColor,
}) {
  const sd = norm(sunDir);
  const data = new Float32Array(width * height * 3);
  for (let y = 0; y < height; y += 1) {
    const theta = (y / height) * Math.PI;
    for (let x = 0; x < width; x += 1) {
      const phi = (x / width) * Math.PI * 2;
      const dx = Math.sin(theta) * Math.cos(phi);
      const dy = Math.cos(theta);
      const dz = Math.sin(theta) * Math.sin(phi);

      let r, g, b;
      if (dy < 0) {
        // Blend the horizon into the ground band across a soft 0.08 strip —
        // a hard step here reads as a giant grey V seam across the sky dome.
        const m = Math.min(1, Math.max(0, (-dy) / 0.12));
        r = horizonColor[0] * (1 - m) + groundColor[0] * m;
        g = horizonColor[1] * (1 - m) + groundColor[1] * m;
        b = horizonColor[2] * (1 - m) + groundColor[2] * m;
      } else {
        // Gradient biased toward a wide haze band near the horizon (overcast
        // dockyard: bright murk low, grey-blue high).
        const t = Math.pow(Math.max(dy, 0), 0.42);
        r = horizonColor[0] * (1 - t) + zenithColor[0] * t;
        g = horizonColor[1] * (1 - t) + zenithColor[1] * t;
        b = horizonColor[2] * (1 - t) + zenithColor[2] * t;

        const dot = dx * sd[0] + dy * sd[1] + dz * sd[2];
        if (dot > 0) {
          const disc = Math.pow(dot, 1200) * sunIntensity;
          // Tight overcast halo + a whisper of broad glow — the old
          // pow(dot,12)*0.35 term painted a giant pale wedge across the sky
          // in the sun's azimuth sector (screenshot-visible "pyramid" bug).
          const halo = Math.pow(dot, 96) * 1.1;
          const glow = Math.pow(dot, 4) * 0.07 + halo;
          r += sunColor[0] * (disc + glow);
          g += sunColor[1] * (disc + glow);
          b += sunColor[2] * (disc + glow);
        }
      }
      // High-value clamp keeps the encoder's shared-exponent math tidy.
      const i = (y * width + x) * 3;
      data[i] = Math.min(r, 64);
      data[i + 1] = Math.min(g, 64);
      data[i + 2] = Math.min(b, 64);
    }
  }
  return { width, height, data };
}

/**
 * Radiance .hdr (uncompressed RGBE) encoder — header + raw 4-byte pixels.
 * RGBE stores v = byte / 256 * 2^(E-128). Encoding: v = m * 2^e with
 * m in [0.5, 1) (frexp), then byte = floor(c * 256 / 2^e), E = e + 128.
 */
function writeRadianceHDR({ width, height, data }, filePath) {
  const header = Buffer.from(
    '#?RADIANCE\n# Generated by tools/generateHDRISky.js — procedural dockyard sky\n'
    + 'FORMAT=32-bit_rle_rgbe\n\n'
    + `-Y ${height} +X ${width}\n`,
    'ascii',
  );
  const pixels = Buffer.alloc(width * height * 4);
  let nanCount = 0; let over64 = 0; let maxV = 0; let maxE = 0;
  for (let i = 0; i < width * height; i += 1) {
    const r = data[i * 3], g = data[i * 3 + 1], b = data[i * 3 + 2];
    const v = Math.max(r, g, b);
    if (Number.isNaN(v)) {
      nanCount += 1;
      pixels.fill(0, i * 4, i * 4 + 4);
      data[i * 3] = 0; data[i * 3 + 1] = 0; data[i * 3 + 2] = 0;
      continue;
    }
    if (v > 64) over64 += 1;
    if (v > maxV) maxV = v;
    if (v < 1e-32) {
      pixels.fill(0, i * 4, i * 4 + 4);
      continue;
    }
    const e = Math.ceil(Math.log2(v));
    const m = v / 2 ** e;                       // in [0.5, 1]
    const mantissa = m <= 0.5 ? m * 2 : m;
    const exponent = m <= 0.5 ? e - 1 : e;
    const scale = 256 / 2 ** exponent;          // byte = c * scale
    pixels[i * 4] = Math.min(255, Math.floor(r * scale));
    pixels[i * 4 + 1] = Math.min(255, Math.floor(g * scale));
    pixels[i * 4 + 2] = Math.min(255, Math.floor(b * scale));
    pixels[i * 4 + 3] = exponent + 128;
    void mantissa;
  }
  fs.writeFileSync(filePath, Buffer.concat([header, pixels]));
  console.log('wrote', filePath, `(${width}x${height})`,
    { nan: nanCount, over64, maxV: Math.round(maxV * 100) / 100, maxE });
}

// --- overcast dockyard sky (matches shipment.json's sunDirection) ----------
const overcastDockyard = generateSkyHDR({
  sunDir: [0.35, 0.62, -0.42],
  sunColor: [6.0, 5.5, 4.6], sunIntensity: 3.6,
  zenithColor: [0.22, 0.26, 0.32],
  horizonColor: [0.52, 0.53, 0.5],
  groundColor: [0.2, 0.19, 0.18],
});
writeRadianceHDR(overcastDockyard, path.join(OUT_DIR, 'overcast_dockyard.hdr'));
